[project]
name = "SSML"
version = "0.1.4"
description = "Stella Sora Mod Launcher"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.1.3",
    "pyside6>=6.10.1",
    "requests>=2.31.0",
    "pywin32>=306",
]

